### ISSUE TITLE
Documentation on getting started

### ISSUE THREAD

**Issue by aryajur** [Wiladams/LuaModeling#1]
Hi,
      I am very new to 3D modelling. It would be nice to have a basic list of steps to get started. Like which part of he OpenSCAD documentation if any should be read and then how to use LuaModeling to create some simple shapes and then move on to complex shapes.

Thanks for the effort on this library.

Milind

**Comment by Wiladams** [comment]
I have been adding code/pictures to the README as I'm adding shapes to the library (porting from BanateCAD).  I'll put some effort into document rudimentary steps and my workflow so it becomes a little more obvious.

Take a look at the examples on the main page though so you get an idea of where things are heading.

**Comment by Wiladams** [comment]
There is documentation there now.  It's from the perspective of LuaModeling though, not OpenSCAD.  If you want to learn OpenSCAD directly, there are tutorials available for that.  LuaModeling is more about the general algorithmic creation of models, which so happen to export to OpenSCAD polyhedron format.
