### ISSUE TITLE
How to create an object off center?

### ISSUE THREAD

**Issue by aryajur** [Wiladams/LuaModeling#3]
I have the following code:

```Lua
local oscad = require "lmodel.openscad_print"
local f = assert(io.open("planetarium.scad", 'w'));
ell = require("lmodel.ellipsoid")
local e1 = ell {
	XRadius = 70,
	ZRadius = -70,
	USteps = 16,
	WSteps = 4,
	MaxPhi = math.pi/2
}
oscad.PolyMesh_print(f,e1:getMesh())
```
How can I place this half sphere off center?

**Comment by Wiladams** [comment]
At the moment, you can not change the coordinates, you'd have to do it externally (like in OpenSCAD).  I have the transform matrices in place, but haven't applied them to the geometries yet.


I could add it most simply by having a 'Transform' field, which is a 4x4 matrix of compound transforms.  Would that be good?

**Comment by aryajur** [comment]
I think that should be good. Does it allow rotation of the shape as well?

**Comment by Wiladams** [comment]
Yes, it will allow rotation, translation, scale.  I will initially put it on the openscad output.  That way you can output multiple instances without messing with the core vertices of the object.

**Comment by Wiladams** [comment]
The the following
```lua
local radians = math.rad

-- From Milind Gupta
local oscad = require "lmodel.openscad_print"
local f = assert(io.open("output/planetarium.scad", 'w'));
local ell = require("lmodel.ellipsoid")
local tform = require("lmodel.transformer")()

tform:translate(70, 70,20)
tform:rotate(radians(30),radians(0),radians(30))
tform:scale(1.5, 1, 1)

local e1 = ell {
	XRadius = 70,
	ZRadius = -70,
	USteps = 16,
	WSteps = 4,
	MaxPhi = math.pi/2
}


oscad.PolyMesh_print(f,e1:getMesh(), tform)
```
Basically, construct a transformer, perform various transforms on it, then pass that to the PolyMesh_print() function.  Still working on how I really want rotations to behave, but translation and scale seem to work as you might expect.

**Comment by Wiladams** [comment]
I believe the Transformer now gives you this ability.

**Comment by aryajur** [comment]
Yes thank you very much. Just haven't explored it fully. Will test it out
soon for a structure.
